# Generated by Django 5.1.4 on 2026-09-20 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_clarity', models.PositiveSmallIntegerField(help_text='Clarity of concepts explained (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_engagement', models.PositiveSmallIntegerField(help_text='How engaging the session was (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_pace', models.PositiveSmallIntegerField(help_text='Pacing of the class (1-5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, help_text='Optional comments or suggestions (max 500 characters).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='The completed class session being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='classes.session')),
                ('student', models.ForeignKey(help_text='The student whose experience this feedback represents.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(help_text='The user who submitted this review (student or parent).', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session feedback',
                'verbose_name_plural': 'session feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
